# In Dockerfile.worker

# Use the same base image for consistency
FROM python:3.10-slim

# Set the working directory
WORKDIR /worker

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the worker code
COPY ./worker /worker

# Command to run the worker script
CMD ["python", "worker.py"]